name: Publish Package to npmjs

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      # Setup .npmrc file to publish to npm
      # See https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
