name: Publish Package to npmjs

on:
  release:
    types: [created]

jobs:
  build:
    uses: adobe/aio-reusable-workflows/.github/workflows/on-release-creation-publish-to-npm.yml@main
    secrets: inherit